import { useState, useEffect } from "react";
import { BackButton } from "../components/Buttons";
import Head from 'next/head'
import { useRouter } from "next/router";
import { ProfileCard } from "../components/ProfileCard";
import villagers from '../data/villagers.json'
import styles from '../styles/Profile.module.css'
import { FooterBar, HeaderBar } from "../components/Bars";
import { Cards } from "../components/Card";


export default function ProfilePage() {
const r = useRouter();
const {index, name, type} = r.query;
const [profileVillager, setProfileVillager] = useState(null);

useEffect(() => {
    let profile;
    if (type === "All") {
      profile = villagers[index];
    } else {
      profile = villagers.find(villager => villager.Name === name && villager.Personality === type);
    }
    setProfileVillager(profile);
  }, [index, name, type]);
  
return (
    <>
      <Head>
        <title>Profile of Villagers in New Horizon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/goldenLeaf.svg" />
      </Head>
      <HeaderBar/>
      <main className={styles.main}>
        <BackButton onBack={()=>r.push('/')}/>
        {profileVillager && 
          <ProfileCard
          title={profileVillager.Name}
            personality={profileVillager.Personality}
            hobby={profileVillager.Hobby}
            species={profileVillager.Species}
            birthday={profileVillager.Birthday}
            catchphrase={profileVillager.Catchphrase}
            image={profileVillager['Photo Image']}
            song={profileVillager['Favorite Song']}
            icon={profileVillager['Icon Image']}
          />}
    </main>
    <FooterBar/>
   </>
)
}